language: node_js
elm-format: 0.8.3
elm-test: 0.19.1
node_js: '12'
before_script:
  - yarn global add elm-test@0.19.1
  - yarn global add elm-format@0.8.3
script:
  - yarn test
jobs:
  include:
    - stage: deploy
      script: yarn prod && tar -zcvf elm-ninja.tar.gz dist
      deploy:
        provider: releases
        cleanup: false
        github_token: $GITHUB_TOKEN
        file: elm-ninja.tar.gz
        